# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

#  config.vm.provision :docker
  config.vm.hostname = "mpivet-pS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.synced_folder "confs/", "/vagrant", type:"virtualbox"
  config.vm.provision :shell, path: "scripts/bootstrap.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "mpivet-pS"
  end

end
